package com.example.jp;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.example.jp.HeadLineDao;
import com.example.jp.NBADao;
import com.example.jp.FinanceDao;
import com.example.jp.EntertainmentDao;
import com.example.jp.ScienceDao;
import com.example.jp.FashionDao;
import com.example.jp.HistoryDao;
import com.example.jp.HomeDao;
import com.example.jp.ChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        HeadLineDao.createTable(db, ifNotExists);
        NBADao.createTable(db, ifNotExists);
        FinanceDao.createTable(db, ifNotExists);
        EntertainmentDao.createTable(db, ifNotExists);
        ScienceDao.createTable(db, ifNotExists);
        FashionDao.createTable(db, ifNotExists);
        HistoryDao.createTable(db, ifNotExists);
        HomeDao.createTable(db, ifNotExists);
        ChannelDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        HeadLineDao.dropTable(db, ifExists);
        NBADao.dropTable(db, ifExists);
        FinanceDao.dropTable(db, ifExists);
        EntertainmentDao.dropTable(db, ifExists);
        ScienceDao.dropTable(db, ifExists);
        FashionDao.dropTable(db, ifExists);
        HistoryDao.dropTable(db, ifExists);
        HomeDao.dropTable(db, ifExists);
        ChannelDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(HeadLineDao.class);
        registerDaoClass(NBADao.class);
        registerDaoClass(FinanceDao.class);
        registerDaoClass(EntertainmentDao.class);
        registerDaoClass(ScienceDao.class);
        registerDaoClass(FashionDao.class);
        registerDaoClass(HistoryDao.class);
        registerDaoClass(HomeDao.class);
        registerDaoClass(ChannelDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
