package com.example.jp;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.jp.HeadLine;
import com.example.jp.NBA;
import com.example.jp.Finance;
import com.example.jp.Entertainment;
import com.example.jp.Science;
import com.example.jp.Fashion;
import com.example.jp.History;
import com.example.jp.Home;
import com.example.jp.Channel;

import com.example.jp.HeadLineDao;
import com.example.jp.NBADao;
import com.example.jp.FinanceDao;
import com.example.jp.EntertainmentDao;
import com.example.jp.ScienceDao;
import com.example.jp.FashionDao;
import com.example.jp.HistoryDao;
import com.example.jp.HomeDao;
import com.example.jp.ChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig headLineDaoConfig;
    private final DaoConfig nBADaoConfig;
    private final DaoConfig financeDaoConfig;
    private final DaoConfig entertainmentDaoConfig;
    private final DaoConfig scienceDaoConfig;
    private final DaoConfig fashionDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig homeDaoConfig;
    private final DaoConfig channelDaoConfig;

    private final HeadLineDao headLineDao;
    private final NBADao nBADao;
    private final FinanceDao financeDao;
    private final EntertainmentDao entertainmentDao;
    private final ScienceDao scienceDao;
    private final FashionDao fashionDao;
    private final HistoryDao historyDao;
    private final HomeDao homeDao;
    private final ChannelDao channelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        headLineDaoConfig = daoConfigMap.get(HeadLineDao.class).clone();
        headLineDaoConfig.initIdentityScope(type);

        nBADaoConfig = daoConfigMap.get(NBADao.class).clone();
        nBADaoConfig.initIdentityScope(type);

        financeDaoConfig = daoConfigMap.get(FinanceDao.class).clone();
        financeDaoConfig.initIdentityScope(type);

        entertainmentDaoConfig = daoConfigMap.get(EntertainmentDao.class).clone();
        entertainmentDaoConfig.initIdentityScope(type);

        scienceDaoConfig = daoConfigMap.get(ScienceDao.class).clone();
        scienceDaoConfig.initIdentityScope(type);

        fashionDaoConfig = daoConfigMap.get(FashionDao.class).clone();
        fashionDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        homeDaoConfig = daoConfigMap.get(HomeDao.class).clone();
        homeDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        headLineDao = new HeadLineDao(headLineDaoConfig, this);
        nBADao = new NBADao(nBADaoConfig, this);
        financeDao = new FinanceDao(financeDaoConfig, this);
        entertainmentDao = new EntertainmentDao(entertainmentDaoConfig, this);
        scienceDao = new ScienceDao(scienceDaoConfig, this);
        fashionDao = new FashionDao(fashionDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        homeDao = new HomeDao(homeDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);

        registerDao(HeadLine.class, headLineDao);
        registerDao(NBA.class, nBADao);
        registerDao(Finance.class, financeDao);
        registerDao(Entertainment.class, entertainmentDao);
        registerDao(Science.class, scienceDao);
        registerDao(Fashion.class, fashionDao);
        registerDao(History.class, historyDao);
        registerDao(Home.class, homeDao);
        registerDao(Channel.class, channelDao);
    }
    
    public void clear() {
        headLineDaoConfig.getIdentityScope().clear();
        nBADaoConfig.getIdentityScope().clear();
        financeDaoConfig.getIdentityScope().clear();
        entertainmentDaoConfig.getIdentityScope().clear();
        scienceDaoConfig.getIdentityScope().clear();
        fashionDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        homeDaoConfig.getIdentityScope().clear();
        channelDaoConfig.getIdentityScope().clear();
    }

    public HeadLineDao getHeadLineDao() {
        return headLineDao;
    }

    public NBADao getNBADao() {
        return nBADao;
    }

    public FinanceDao getFinanceDao() {
        return financeDao;
    }

    public EntertainmentDao getEntertainmentDao() {
        return entertainmentDao;
    }

    public ScienceDao getScienceDao() {
        return scienceDao;
    }

    public FashionDao getFashionDao() {
        return fashionDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public HomeDao getHomeDao() {
        return homeDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

}
